name: vice-jz
version: '3.6.1'
summary: Versatile Commodore Emulator
description: |
  VICE executes programs intended for the old 8-bit computers. It currently 
  emulates the C64, the C64DTV, the C128, the VIC20, practically all PET
  models, the PLUS4 and the CBM-II (aka C610/C510). An extra emulator is
  provided for C64 expanded with the CMD SuperCPU. 

grade: stable
confinement: strict
base: core22

plugs:
    gnome-3-28-1804:
        interface: content
        target: $SNAP/gnome-platform
        default-provider: gnome-3-28-1804
    gtk-3-themes:
        interface: content
        target: $SNAP/share/themes
        default-provider: gtk-common-themes:gtk-3-themes
    icon-themes:
        interface: content
        target: $SNAP/share/icons
        default-provider: gtk-common-themes:icon-themes
    sound-themes:
        interface: content
        target: $SNAP/share/sounds
        default-provider: gtk-common-themes:sounds-themes

environment:
    XDG_DATA_DIRS: $SNAP/data-dir:$XDG_DATA_DIRS
    GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
    GTK_USE_PORTAL: 1

apps:
  c1541:
    command: desktop-launch c1541
    plugs: [home]

  cartconv:
    command: cartconv
    plugs: [home]

  petcat:
    command: petcat
    plugs: [home]

  vsid:
    command: vsid
    plugs: [home]

  x128:
    command: desktop-launch x128
    plugs: [home, x11, wayland, gsettings, desktop, desktop-legacy, pulseaudio, joystick, network-bind, network, io-ports-control]

  x64:
    command: desktop-launch x64
    plugs: [home, x11, wayland, gsettings, desktop, desktop-legacy, pulseaudio, joystick, network-bind, network, io-ports-control]

  x64dtv:
    command: desktop-launch x64dtv
    plugs: [home, x11, wayland, gsettings, desktop, desktop-legacy, pulseaudio, joystick, network-bind, network, io-ports-control]

  x64sc:
    command: desktop-launch x64sc
    plugs: [home, x11, wayland, gsettings, desktop, desktop-legacy, pulseaudio, joystick, network-bind, network, io-ports-control]

  xcbm2:
    command: desktop-launch xcbm2
    plugs: [home, x11, wayland, gsettings, desktop, desktop-legacy, pulseaudio, joystick, network-bind, network, io-ports-control]

  xcbm5x0:
    command: desktop-launch xcbm5x0
    plugs: [home, x11, wayland, gsettings, desktop, desktop-legacy, pulseaudio, joystick, network-bind, network, io-ports-control]

  xpet:
    command: desktop-launch xpet
    plugs: [home, x11, wayland, gsettings, desktop, desktop-legacy, pulseaudio, joystick, network-bind, network, io-ports-control]

  xplus4:
    command: desktop-launch xplus4
    plugs: [home, x11, wayland, gsettings, desktop, desktop-legacy, pulseaudio, joystick, network-bind, network, io-ports-control]

  xscpu64:
    command: desktop-launch xscpu64
    plugs: [home, x11, wayland, gsettings, desktop, desktop-legacy, pulseaudio, joystick, network-bind, network, io-ports-control]

  xvic:
    command: desktop-launch xvic
    plugs: [home, x11, wayland, gsettings, desktop, desktop-legacy, pulseaudio, joystick, network-bind, network, io-ports-control]

parts:
  vice:
    source: https://downloads.sourceforge.net/project/vice-emu/releases/vice-3.6.1.tar.gz
    plugin: autotools
    configflags:
      - --prefix=/snap/vice-jz/current
      - --enable-native-gtk3ui
      - --disable-parsid
      - --enable-arch=no
      - --with-jpeg
      - --enable-lame
      - --with-pulse
    build-packages:
      - bison
      - xa65
      - flex
      - texinfo
      - libreadline-dev
      - libjpeg-dev
      - libpng-dev
      - libgtk-3-dev
      - libasound2-dev
      - libpulse-dev
      - libmp3lame-dev
      - libavformat-dev
      - libieee1284-3-dev
      - libgtkglext1-dev
      - libswscale-dev
      - xfonts-utils
      - yasm
    prime:
      - -var
      - -share/info
      - -share/man
      - -usr/share/alsa
      - -usr/share/apport
      - -usr/share/avahi
      - -usr/share/bug
      - -usr/share/dbus-1
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/icons
      - -usr/share/libthai
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/mime
      - -usr/share/pkgconfig
      - -snap
    organize:
      snap/vice-jz/current/bin: bin
      snap/vice-jz/current/lib64: lib64
      snap/vice-jz/current/share: share
    after:
      - desktop-gnome-platform
    override-build: |
      snapcraftctl build
      echo Stripping executables
      strip $SNAPCRAFT_PART_INSTALL/snap/vice-jz/current/bin/*

  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  # workaround snapcraft trying to outsmart us by copying ldd listed libraries
  workaround:
    plugin: nil
    prime:
      - "-*"

